# -*- coding: utf-8 -*-
"""data_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vm63Op8enEeesSByeq_VmE7Y-jQ5VfjR
"""

!pip -q install pandas numpy scikit-learn beautifulsoup4 lxml tqdm

import re
import os
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
from tqdm import tqdm

tqdm.pandas()

from google.colab import files
uploaded = files.upload()

file_name = list(uploaded.keys())[0]
print("Uploaded:", file_name)
df = pd.read_csv(file_name)
df.head()

print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
df.sample(5)

df.columns = [c.strip().lower() for c in df.columns]

# Possible column guesses
possible_subject = ["subject", "email_subject", "title"]
possible_body    = ["body", "email_body", "message", "text", "content"]

def pick_col(possible, cols):
    for c in possible:
        if c in cols:
            return c
    return None

subject_col = pick_col(possible_subject, df.columns)
body_col    = pick_col(possible_body, df.columns)

print("Detected subject_col:", subject_col)
print("Detected body_col:", body_col)

if body_col is None:
    raise ValueError("Body/text column not found. Rename your dataset column to one of: " + str(possible_body))

if subject_col is None:
    # If subject doesn't exist, create empty subject
    df["subject"] = ""
    subject_col = "subject"

df["subject"] = df[subject_col].fillna("").astype(str)
df["body"]    = df[body_col].fillna("").astype(str)

df["raw_text"] = (df["subject"].str.strip() + " " + df["body"].str.strip()).str.strip()
df[["subject", "body", "raw_text"]].head()

URL_RE = re.compile(r"(https?://\S+|www\.\S+)")
EMAIL_RE = re.compile(r"\b[\w\.-]+@[\w\.-]+\.\w+\b")
PHONE_RE = re.compile(r"\b(\+?\d[\d\-\s]{8,}\d)\b")

SIGNOFF_PATTERNS = [
    r"\bregards\b", r"\bkind regards\b", r"\bthanks\b", r"\bthank you\b",
    r"\bsincerely\b", r"\bbest\b", r"\bbest regards\b", r"\byours truly\b"
]

def strip_html(text: str) -> str:
    # remove html tags safely
    soup = BeautifulSoup(text, "lxml")
    return soup.get_text(" ")

def normalize_text(text: str) -> str:
    text = text.lower()
    text = URL_RE.sub(" ", text)
    text = EMAIL_RE.sub(" ", text)
    text = PHONE_RE.sub(" ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

def remove_forward_reply_blocks(text: str) -> str:
    # remove typical email reply chains
    patterns = [
        r"-----original message-----.*",
        r"from:.*\n.*(sent:|date:).*",
        r"on .* wrote:.*"
    ]
    for p in patterns:
        text = re.sub(p, " ", text, flags=re.IGNORECASE | re.DOTALL)
    return text

def remove_signature(text: str) -> str:
    # cut off after signoff words if appears near end
    for pat in SIGNOFF_PATTERNS:
        m = re.search(pat, text, flags=re.IGNORECASE)
        if m and (len(text) - m.start()) < 250:  # signoff near end
            return text[:m.start()].strip()
    return text

def clean_email(text: str) -> str:
    text = strip_html(text)
    text = remove_forward_reply_blocks(text)
    text = normalize_text(text)
    text = remove_signature(text)
    # keep basic characters
    text = re.sub(r"[^a-z0-9\s\.\,\!\?\-]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

df["clean_text"] = df["raw_text"].progress_apply(clean_email)

df[["raw_text", "clean_text"]].sample(5)

df["clean_len"] = df["clean_text"].str.split().apply(len)
df = df[df["clean_len"] >= 3].copy()

print("After removing short emails:", df.shape)
df[["clean_text", "clean_len"]].head()

label_cols = [c for c in df.columns if c in ["category", "label", "class", "urgency", "priority"]]
print("Possible existing label columns:", label_cols)

CATEGORY_KEYWORDS = {
    "complaints": [
        "not working", "issue", "problem", "error", "failed", "broken", "complaint",
        "bad service", "delay", "refund", "charged", "billing issue", "cancel"
    ],
    "requests": [
        "please", "could you", "can you", "request", "need", "want", "help me",
        "support", "assist", "how to", "guide", "update", "change"
    ],
    "feedback": [
        "feedback", "suggestion", "appreciate", "thank", "great", "good", "love",
        "improve", "rating", "review"
    ],
    "spam": [
        "win", "free", "offer", "click", "buy now", "limited time", "promo",
        "congratulations", "prize", "lottery", "urgent response needed"
    ]
}

def label_category(text: str) -> str:
    t = text.lower()
    scores = {}
    for cat, kws in CATEGORY_KEYWORDS.items():
        scores[cat] = sum(1 for kw in kws if kw in t)
    best_cat = max(scores, key=scores.get)
    if scores[best_cat] == 0:
        # default heuristic: if contains promo style => spam else request
        return "requests"
    return best_cat

df["category"] = df["clean_text"].progress_apply(label_category)
df["category"].value_counts()

HIGH_URGENCY = ["urgent", "asap", "immediately", "not working", "down", "failed", "can't access", "service outage"]
MED_URGENCY  = ["soon", "priority", "quick", "delay", "pending", "follow up"]
LOW_URGENCY  = ["whenever", "no rush", "later", "just asking", "FYI"]

def label_urgency(text: str) -> str:
    t = text.lower()
    if any(k in t for k in HIGH_URGENCY):
        return "high"
    if any(k in t for k in MED_URGENCY):
        return "medium"
    if any(k in t for k in LOW_URGENCY):
        return "low"
    # fallback: complaints often higher
    return "medium"

df["urgency"] = df["clean_text"].progress_apply(label_urgency)
df["urgency"].value_counts()

if "date" not in df.columns:
    df["date"] = pd.Timestamp.today().date()

df[["date", "category", "urgency", "clean_text"]].head()

final_df = df[["subject", "body", "clean_text", "category", "urgency", "date"]].copy()
final_df.drop_duplicates(subset=["clean_text"], inplace=True)

print("Final dataset shape:", final_df.shape)
final_df.sample(5)

out_path = "processed_emails.csv"
final_df.to_csv(out_path, index=False)
print("Saved:", out_path)

from google.colab import files
files.download("processed_emails.csv")