# -*- coding: utf-8 -*-
"""email_categorization_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iS5nPoJ18mzMfSw984Zg1P66GByB4Ynx
"""

!pip -q install pandas numpy scikit-learn joblib matplotlib

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import joblib
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()

file_name = list(uploaded.keys())[0]
print("Uploaded:", file_name)

df = pd.read_csv(file_name)
df.head()

print("Shape:", df.shape)
print(df["category"].value_counts())

# ensure required columns
assert "clean_text" in df.columns, "clean_text column missing"
assert "category" in df.columns, "category column missing"

X = df["clean_text"].fillna("").astype(str)
y = df["category"].fillna("").astype(str)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Train:", X_train.shape, "Test:", X_test.shape)

lr_clf = Pipeline([
    ("tfidf", TfidfVectorizer(
        ngram_range=(1,2),
        min_df=2,
        max_df=0.95,
        sublinear_tf=True
    )),
    ("model", LogisticRegression(
        max_iter=2000,
        class_weight="balanced",
        n_jobs=-1
    ))
])

lr_clf.fit(X_train, y_train)
print("LR training done")

lr_pred = lr_clf.predict(X_test)

print("LR Accuracy:", accuracy_score(y_test, lr_pred))
print("\nClassification Report (LR):\n")
print(classification_report(y_test, lr_pred))

labels = sorted(y.unique())
cm = confusion_matrix(y_test, lr_pred, labels=labels)

plt.figure(figsize=(7,5))
plt.imshow(cm)
plt.xticks(range(len(labels)), labels, rotation=45)
plt.yticks(range(len(labels)), labels)
plt.title("Confusion Matrix - Logistic Regression")
plt.colorbar()
plt.show()

cm

nb_clf = Pipeline([
    ("tfidf", TfidfVectorizer(
        ngram_range=(1,2),
        min_df=2,
        max_df=0.95
    )),
    ("model", MultinomialNB(alpha=0.5))
])

nb_clf.fit(X_train, y_train)
print("NB training done ")

nb_pred = nb_clf.predict(X_test)

print("NB Accuracy:", accuracy_score(y_test, nb_pred))
print("\nClassification Report (NB):\n")
print(classification_report(y_test, nb_pred))

results = pd.DataFrame({
    "clean_text": X_test,
    "true_category": y_test,
    "pred_lr": lr_pred,
    "pred_nb": nb_pred
})

results.to_csv("category_results.csv", index=False)
print("Saved: category_results.csv ")
results.head()

joblib.dump(lr_clf, "category_model_lr.pkl")
joblib.dump(nb_clf, "category_model_nb.pkl")

print("Saved models")