# -*- coding: utf-8 -*-
"""email_categorization_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TrZ5RKmEaC-axQXfPKeSP2-bgzgKFtIN
"""

!pip install scikit-learn -q

import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

train_df = pd.read_csv("clean_email  (1).csv")
test_df = pd.read_csv("test_clean_email (1).csv")

print("Train:", train_df.shape)
print("Test:", test_df.shape)

X_train = train_df['clean_text']
y_train = train_df['Category']

X_test = test_df['clean_text']
y_test = test_df['Category']

vectorizer = TfidfVectorizer(
    max_features=8000,
    ngram_range=(1,2),
    min_df=2
)

X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

lr_model = LogisticRegression(max_iter=1000, class_weight='balanced')
lr_model.fit(X_train_tfidf, y_train)

y_pred_lr = lr_model.predict(X_test_tfidf)

print("🔹 Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr))

nb_model = MultinomialNB()
nb_model.fit(X_train_tfidf, y_train)

y_pred_nb = nb_model.predict(X_test_tfidf)

print("🔹 Naive Bayes Accuracy:", accuracy_score(y_test, y_pred_nb))
print(classification_report(y_test, y_pred_nb))

svm_model = LinearSVC(class_weight='balanced', C=1.5)
svm_model.fit(X_train_tfidf, y_train)

y_pred_svm = svm_model.predict(X_test_tfidf)

print("SVM Accuracy:", accuracy_score(y_test, y_pred_svm))
print(classification_report(y_test, y_pred_svm))

cm = confusion_matrix(y_test, y_pred_svm)

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')

plt.title("Confusion Matrix - SVM")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

def predict_email(text):
    vec = vectorizer.transform([text])
    return svm_model.predict(vec)[0]

print(predict_email("Your OTP code is 1234"))
print(predict_email("Get 70% discount now"))
print(predict_email("Join our community discussion"))

import joblib

joblib.dump(svm_model, "svm_email_classifier.pkl")

joblib.dump(vectorizer, "tfidf_vectorizer.pkl")

from google.colab import files

files.download("svm_email_classifier.pkl")
files.download("tfidf_vectorizer.pkl")

import joblib

svm_model = joblib.load("svm_email_classifier.pkl")
vectorizer = joblib.load("tfidf_vectorizer.pkl")