# -*- coding: utf-8 -*-
"""modul3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qSbdLv7CL6WGwMWtQ68-bsJd5e_oxmra
"""

!pip install scikit-learn joblib -q

import pandas as pd
import re
import joblib

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

from google.colab import files
uploaded = files.upload()

train_df = pd.read_csv("clean_email .csv")
test_df = pd.read_csv("test_clean_email.csv")

print("Train Shape:", train_df.shape)
print("Test Shape:", test_df.shape)

print(train_df["Urgency"].value_counts())

HIGH_PATTERNS = [
    r"urgent", r"asap", r"immediately",
    r"not working", r"error", r"failed",
    r"account blocked", r"refund issue"
]

MED_PATTERNS = [
    r"follow up", r"need help"
]

def rule_based_urgency(text):
    t = str(text).lower()

    for pat in HIGH_PATTERNS:
        if re.search(pat, t):
            return "High"

    for pat in MED_PATTERNS:
        if re.search(pat, t):
            return "Medium"

    return "Low"

vectorizer = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1,2)
)

X_train = vectorizer.fit_transform(train_df['clean_text'])
X_test = vectorizer.transform(test_df['clean_text'])

y_train = train_df['Urgency']
y_test = test_df['Urgency']

from sklearn.svm import LinearSVC
model = LinearSVC(class_weight='balanced')
model.fit(X_train, y_train)

def hybrid_urgency(text):
    vec = vectorizer.transform([text])
    ml_pred = model.predict(vec)[0]

    rule_pred = rule_based_urgency(text)

    # Only upgrade LOW predictions
    if ml_pred == "Low" and rule_pred == "High":
        return "High"

    if ml_pred == "Low" and rule_pred == "Medium":
        return "Medium"

    return ml_pred

predictions = test_df['clean_text'].apply(hybrid_urgency)

print("Final Accuracy:", accuracy_score(y_test, predictions))
print("\nClassification Report:\n")
print(classification_report(y_test, predictions))

print(hybrid_urgency("My account is not working, urgent help needed"))
print(hybrid_urgency("Please follow up on my request"))
print(hybrid_urgency("Check this offer now"))

joblib.dump(model, "urgency_model.pkl")
joblib.dump(vectorizer, "urgency_vectorizer.pkl")

print("Models saved successfully!")

from google.colab import files

files.download("urgency_model.pkl")
files.download("urgency_vectorizer.pkl")